// src/app/pricing/layout.tsx
import type { Metadata } from "next";
import "../globals.css";

// ✅ Use the objects from the geist package (no function call)
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PricingLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
      {children}
    </div>
  );
}
