import type { Metadata } from "next";
import "./globals.css";
import dynamic from "next/dynamic";
import Footer from "./components/Footer";
import AuthProvider from "./providers/AuthProvider";

const Navbar = dynamic(() => import("./components/Navbar"));

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect to Google Fonts to improve loading performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* Load Google Fonts with font-display: swap */}
        <link 
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@400;500;600;700&family=Montserrat:wght@400;500;600;700&display=swap" 
          rel="stylesheet" 
        />
      </head>
      <body
        className="font-sans antialiased"
      >
        {/* Scope session context to Navbar only to avoid global client hydration */}
        <AuthProvider>
          <Navbar />
        </AuthProvider>
        {children}
        <Footer />
      </body>
    </html>
  );
}
